# Generated by Django 5.2.1 on 2025-06-20 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('close', models.FloatField()),
                ('rsi', models.FloatField(blank=True, null=True)),
                ('sma_14', models.FloatField(blank=True, null=True)),
                ('sma_20', models.FloatField(blank=True, null=True)),
                ('macd_line', models.FloatField(blank=True, null=True)),
                ('macd_signal', models.FloatField(blank=True, null=True)),
                ('bb_upper', models.FloatField(blank=True, null=True)),
                ('bb_middle', models.FloatField(blank=True, null=True)),
                ('bb_lower', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('symbol', 'date')},
            },
        ),
    ]
