# Generated by Django 5.2.3 on 2025-06-29 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockindicator',
            name='atr_14',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockindicator',
            name='ema_20',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockindicator',
            name='obv',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockindicator',
            name='stochrsi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockindicator',
            name='wma_20',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
