# Generated by Django 5.2.3 on 2025-07-10 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_stockindicator_atr_14_stockindicator_ema_20_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackedStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10, unique=True)),
            ],
        ),
    ]
