# Generated by Django 5.2.3 on 2025-10-22 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_trackedstock_user_alter_trackedstock_symbol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockindicator',
            name='symbol',
            field=models.CharField(max_length=20),
        ),
    ]
