# Generated by Django 5.2.3 on 2025-10-23 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_alter_stockindicator_symbol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockindicator',
            name='atr_14',
        ),
        migrations.RemoveField(
            model_name='stockindicator',
            name='bb_middle',
        ),
        migrations.RemoveField(
            model_name='stockindicator',
            name='ema_20',
        ),
        migrations.RemoveField(
            model_name='stockindicator',
            name='macd_signal',
        ),
        migrations.RemoveField(
            model_name='stockindicator',
            name='obv',
        ),
        migrations.RemoveField(
            model_name='stockindicator',
            name='sma_20',
        ),
        migrations.RemoveField(
            model_name='stockindicator',
            name='stochrsi',
        ),
        migrations.RemoveField(
            model_name='stockindicator',
            name='wma_20',
        ),
        migrations.AlterField(
            model_name='trackedstock',
            name='symbol',
            field=models.CharField(max_length=20),
        ),
    ]
